#pragma once

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM_THUMB 125

#define HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD

#define COMBO_COUNT 3
#define COMBO_TERM 40

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 2000

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define MASTER_LEFT
