#pragma once

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM_THUMB 125
#define DEBOUNCE 10

#define HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD

#define COMBO_COUNT 6
#define COMBO_TERM 40

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 2000

#undef VENDOR_ID
#define VENDOR_ID 0x4451
#undef PRODUCT_ID
#define PRODUCT_ID 0x0001

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define MASTER_LEFT

// Some KVMs are slow to re-establish active USB communication after switching.
#define SPLIT_USB_TIMEOUT 5000
#define SPLIT_USB_TIMEOUT_POLL 25
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 5500
#define USB_SUSPEND_WAKEUP_DELAY 200
